// <auto-generated />
using System;
using CarParkManagement.Database.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarParkManagement.Database.Migrations
{
    [DbContext(typeof(CarParkManagementDbContext))]
    partial class CarParkManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarParkManagement.Database.Entities.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ParkingSpaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParkingSpaceId1")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("CarId");

                    b.HasIndex("ParkingSpaceId")
                        .IsUnique();

                    b.HasIndex("ParkingSpaceId1")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarParkManagement.Database.Entities.ParkingSpace", b =>
                {
                    b.Property<int>("ParkingSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParkingSpaceId"));

                    b.Property<DateTime?>("OccupiedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParkingSpaceId");

                    b.ToTable("ParkingSpaces");
                });

            modelBuilder.Entity("CarParkManagement.Database.Entities.Car", b =>
                {
                    b.HasOne("CarParkManagement.Database.Entities.ParkingSpace", null)
                        .WithOne()
                        .HasForeignKey("CarParkManagement.Database.Entities.Car", "ParkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarParkManagement.Database.Entities.ParkingSpace", null)
                        .WithOne("Car")
                        .HasForeignKey("CarParkManagement.Database.Entities.Car", "ParkingSpaceId1");
                });

            modelBuilder.Entity("CarParkManagement.Database.Entities.ParkingSpace", b =>
                {
                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
