services:
  carparkmanagement:
    image: carparkmanagement
    build:
      context: .
      dockerfile: CarParkManagement/Dockerfile
  
  postgres:
    image: postgres:17-alpine
    container_name: carparkmanagement-db
    environment:
      POSTGRES_DB: carpark_dev
      POSTGRES_USER: carpark_user
      POSTGRES_PASSWORD: carpark_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
